name: CI MLflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas scikit-learn numpy

      # Run MLflow Project
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      # Verify mlruns exists
      - name: Check MLflow Artifacts
        run: |
          ls -R mlruns

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/